# Generated by Django 5.1.2 on 2024-11-17 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kmStoreApp', '0003_alter_carrito_usuario_alter_ordenenvio_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('stock_maximo', models.PositiveIntegerField(default=100)),
                ('punto_reorden', models.PositiveIntegerField(default=10)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kmStoreApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada de Stock'), ('SALIDA', 'Salida de Stock'), ('AJUSTE', 'Ajuste de Inventario'), ('VENTA', 'Venta')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmStoreApp.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
