# Generated by Django 5.1 on 2024-12-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmBoletas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='subtotal',
            field=models.PositiveIntegerField(),
        ),
    ]
