# Generated by Django 5.0.2 on 2024-12-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmBoletas', '0002_alter_boleta_total_alter_detalleboleta_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
