# Generated by Django 5.1 on 2024-12-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmStoreApp', '0003_alter_carrito_usuario_alter_ordenenvio_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
